name: Some Tests

on: push
jobs: 
    my_tests:
        runs-on: ubuntu-latest
        container: dolfinx/dolfinx

        steps: 
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: | 
                  pip3 install pytest matplotlib
            - name: Run the tests
              run: | 
                  cd code 
                  pytest
